// apps/demo-solid/src/components/Card.tsx
import type { JSX } from 'solid-js';

interface CardProps {
	title: string;
	onAddClick?: () => void;
	children: JSX.Element;
	class?: string;
}

export function Card(props: CardProps) {
	return (
		<div
			class={`bg-white/30 shadow rounded-lg p-3 h-80 overflow-y-auto border border-white/10 ${props.class || ''}`}
		>
			<div class="flex items-center justify-between mb-5">
				<h3 class="font-bold text-white">{props.title}</h3>
				{props.onAddClick && (
					<button
						onClick={props.onAddClick}
						class="rounded-full active:scale-105 transition-all size-6 border border-white/10 flex items-center justify-center bg-white/10 shadow hover:bg-white/20"
					>
						<span class="text-white text-sm">+</span>
					</button>
				)}
			</div>
			{props.children}
		</div>
	);
}

// apps/demo-react/src/components/Card.tsx
import { PlusIcon } from '@heroicons/react/24/solid';
import { cva } from 'cva';
import type { ReactNode } from 'react';

interface CardProps {
	title: string;
	onAddClick?: () => void;
	children: ReactNode;
	className?: string;
}

export const card = cva({
	base: 'p-2 bg-gray-100 border border-gray-200 rounded-lg h-full',
});

export function Card({ title, onAddClick, children, className }: CardProps) {
	return (
		<div className={card({ className })}>
			<div className="flex items-center justify-between">
				<h2 className="font-bold p-3">{title}</h2>
				{onAddClick && (
					<button
						type="button"
						className="rounded-full transition-all size-8 flex items-center justify-center bg-gray-50 border border-gray-200"
						onClick={onAddClick}
					>
						<PlusIcon className="size-4" />
					</button>
				)}
			</div>
			{children}
		</div>
	);
}
