// apps/demo-solid/src/components/IngredientCombobox.tsx
import type { Ingredient } from '@byearlybird/demo-shared';
import { For, createEffect, createSignal, onMount } from 'solid-js';
import { useStore } from './StoreProvider';

interface IngredientComboboxProps {
	onSelect: (ingredient: Ingredient) => void;
	exclude?: string[];
}

export function IngredientCombobox(props: IngredientComboboxProps) {
	const ingredientStore = useStore('ingredients');
	const [allIngredients, setAllIngredients] = createSignal<Ingredient[]>([]);
	const [availableIngredients, setAvailableIngredients] = createSignal<
		Ingredient[]
	>([]);
	const [selectedId, setSelectedId] = createSignal('');

	const loadAllIngredients = async () => {
		const data = await ingredientStore.all();
		if (data) {
			const ingredients = Object.values(data).filter((i) => !i.isDeleted);
			setAllIngredients(ingredients);
		}
	};

	// Filter available ingredients when exclude list changes
	createEffect(() => {
		const available = allIngredients().filter(
			(i) => !props.exclude?.includes(i.id),
		);
		setAvailableIngredients(available);

		// Reset selection if current selection is now excluded
		if (selectedId() && props.exclude?.includes(selectedId())) {
			setSelectedId('');
		}
	});

	onMount(() => {
		loadAllIngredients();
	});

	const handleSelect = () => {
		const ingredient = availableIngredients().find(
			(i) => i.id === selectedId(),
		);
		if (ingredient) {
			props.onSelect(ingredient);
			setSelectedId(''); // Reset selection
		}
	};

	return (
		<div class="flex gap-2 items-center">
			<select
				class="bg-black/5 border border-black/5 rounded-2xl px-2 py-1 focus:outline-none text-sm focus:border-white/5 transition-all"
				value={selectedId()}
				onInput={(e) => setSelectedId(e.target.value)}
			>
				<option value="" disabled>
					Add an ingredient...
				</option>
				<For each={availableIngredients()}>
					{(ingredient) => (
						<option value={ingredient.id}>{ingredient.name}</option>
					)}
				</For>
			</select>
			<button
				onClick={handleSelect}
				disabled={!selectedId() || availableIngredients().length === 0}
				class="px-2 py-1 bg-blue-600 text-white rounded text-xs disabled:opacity-50 disabled:cursor-not-allowed hover:bg-blue-700 transition-colors"
			>
				Add
			</button>
		</div>
	);
}

// apps/demo-react/src/components/IngredientCombobox.tsx
import type { Ingredient } from '@byearlybird/demo-shared';

import {
	Combobox,
	ComboboxInput,
	ComboboxOption,
	ComboboxOptions,
} from '@headlessui/react';
import { useState } from 'react';
import { useQuery } from './StoreProvider';

export function IngredientCombobox({
	onSelect,
	exclude = [],
}: {
	onSelect: (ingredient: Ingredient) => void;
	exclude?: string[];
}) {
	const [query, setQuery] = useState('');

	const { data: options } = useQuery(
		'ingredients',
		(data) =>
			Object.values(data).filter(
				(i) =>
					!i.isDeleted &&
					!exclude.includes(i.id) &&
					i.name.toLowerCase().includes(query.toLowerCase().toString()),
			),
		[query, exclude],
	);

	return (
		<Combobox
			onChange={(ingredient: Ingredient) => {
				if (ingredient) {
					onSelect(ingredient);
				}
				// setQuery('');
			}}
		>
			<ComboboxInput
				className="bg-black/5 border border-black/5 rounded-2xl px-2 py-1 focus:outline-none text-sm w-1/2 focus:border-white/5 transition-all"
				displayValue={() => query}
				placeholder="Add an ingredient..."
				onChange={(event) => setQuery(event.target.value)}
			/>
			<ComboboxOptions
				anchor={{ to: 'bottom start', gap: '4px' }}
				className="border w-[var(--input-width)] empty:invisible bg-white/5 border-white/5 backdrop-blur-sm rounded-2xl"
			>
				{options.length > 0 ? (
					options.map((ingredient) => (
						<ComboboxOption
							key={ingredient.id}
							value={ingredient}
							className="p-2 text-sm data-focus:bg-black/5 "
						>
							{ingredient.name}
						</ComboboxOption>
					))
				) : (
					<ComboboxOption
						value={null}
						disabled
						className="p-2 text-sm data-focus:bg-black/5 text-white/70"
					>
						No results found
					</ComboboxOption>
				)}
			</ComboboxOptions>
		</Combobox>
	);
}
