// apps/demo-solid/src/components/Ingredients.tsx
import { createSignal, Index, onMount } from 'solid-js';
import { useStore } from './StoreProvider';

export function Ingredients() {
	const ingredientStore = useStore('ingredients');
	const recipeStore = useStore('recipes');
	const [ingredients, setIngredients] = createSignal([]);

	const loadIngredients = async () => {
		const data = await ingredientStore.all();
		if (data) {
			setIngredients(Object.values(data).filter(i => !i.isDeleted));
		}
	};

	// Load ingredients on mount
	onMount(() => {
		loadIngredients();
	});

	const handleAddIngredient = async () => {
		const id = crypto.randomUUID();
		await ingredientStore.create(id, {
			id,
			name: '',
			isDeleted: false,
		});
		await loadIngredients();
	};

	const handleUpdateIngredient = async (id: string, name: string) => {
		await ingredientStore.update(id, { name });
		
		// Update ingredient names in all recipes that use this ingredient
		const allRecipes = await recipeStore.all();
		if (!allRecipes) return;

		const recipesToUpdate = Object.values(allRecipes).filter((r) =>
			r.ingredients.some((i) => i.id === id),
		);

		const updatePromises = recipesToUpdate.map((recipe) =>
			recipeStore.update(recipe.id, {
				ingredients: recipe.ingredients.map((i) =>
					i.id === id ? { ...i, name } : i,
				),
			})
		);

		await Promise.all(updatePromises);
		await loadIngredients();
	};

	const handleIngredientBlur = async (id: string, name: string) => {
		if (name.trim() === '') {
			await ingredientStore.update(id, { isDeleted: true });
			await loadIngredients();
		}
	};

	return (
		<div class="bg-white/30 shadow rounded-lg p-3 h-80 overflow-y-auto border border-white/10">
			<div class="flex items-center justify-between mb-5">
				<h3 class="font-bold text-white">All Ingredients</h3>
				<button 
					onClick={handleAddIngredient}
					class="rounded-full active:scale-105 transition-all size-6 border border-white/10 flex items-center justify-center bg-white/10 shadow hover:bg-white/20"
				>
					<span class="text-white text-sm">+</span>
				</button>
			</div>
			<ul class="space-y-2">
				<Index each={ingredients()}>
					{(ingredient, i) => (
						<li class="p-2.5 rounded-lg hover:bg-black/5 transition-all flex items-center gap-2 w-full focus-within:ring focus-within:ring-white/10 outline-none">
							<span class="rounded-full bg-black/10 size-6 text-sm p-0.5 flex items-center justify-center uppercase font-medium text-white">
								{ingredient().name.slice(0, 1)}
							</span>
							<input
								class="w-full focus:outline-none bg-transparent text-white placeholder-white/50"
								value={ingredient().name}
								onInput={(e) => handleUpdateIngredient(ingredient().id, e.target.value)}
								onBlur={(e) => handleIngredientBlur(ingredient().id, e.target.value)}
								placeholder="Ingredient name"
								autofocus={ingredient().name === ''}
							/>
						</li>
					)}
				</Index>
				{ingredients().length === 0 && (
					<p class="text-white/60 text-center mt-10 text-sm">
						No ingredients yet. Click + to add some!
					</p>
				)}
			</ul>
		</div>
	);
}

// apps/demo-react/src/components/Ingredients.tsx
import { PlusIcon } from '@heroicons/react/24/solid';
import { useQuery, useStore } from './StoreProvider';

export function Ingredients() {
	const recipeStore = useStore('recipes');
	const ingredientStore = useStore('ingredients');
	const { data: ingredients } = useQuery(
		'ingredients',
		(data) => Object.values(data).filter((i) => !i.isDeleted),
	);

	const handleAddIngredient = async () => {
		const id = crypto.randomUUID();

		await ingredientStore.create(id, {
			id,
			name: '',
			isDeleted: false,
		});
	};

	const handleUpdateIngredient = async (id: string, name: string) => {
		await ingredientStore.update(id, { name });
		const allRecipes = await recipeStore.all();
		if (!allRecipes) return;

		const toUpdate = Object.values(allRecipes).filter((r) =>
			r.ingredients.some((i) => i.id === id),
		);

		await recipeStore.updateMany(
			toUpdate.map((recipe) => ({
				id: recipe.id,
				value: {
					ingredients: recipe.ingredients.map((i) =>
						i.id === id ? { ...i, name } : i,
					),
				},
			})),
		);
	};

	return (
		<div className="bg-white/30 shadow rounded-lg p-3 h-full border border-white/10">
			<div className="flex items-center justify-between">
				<h2 className="font-bold p-3">Ingredients</h2>
				<button
					type="button"
					className="rounded-full active:scale-105 transition-all size-6 border border-white/10 flex items-center justify-center bg-white/10 shadow"
					onClick={handleAddIngredient}
				>
					<PlusIcon className="size-4 m-auto" />
				</button>
			</div>
			<ul>
				{ingredients?.map((ingredient) => (
					<>
						<li
							key={ingredient.id}
							className="p-2.5 rounded-lg hover:bg-black/5 transition-all flex items-center gap-2 w-full focus-within:ring focus-within:ring-white/10 outline-none "
						>
							<span className="rounded-full bg-black/10 size-6 text-sm p-0.5 flex items-center justify-center uppercase font-medium">
								{ingredient.name.slice(0, 1)}
							</span>
							<input
								// biome-ignore lint/a11y/noAutofocus: <TODO: find a more accesible way to do this>
								autoFocus={ingredient.name === ''}
								onBlur={() => {
									if (ingredient.name === '') {
										ingredientStore.update(ingredient.id, { isDeleted: true });
									}
								}}
								className="w-full focus:outline-none"
								value={ingredient.name}
								onChange={(e) =>
									handleUpdateIngredient(ingredient.id, e.target.value)
								}
							/>
						</li>
					</>
				))}
			</ul>
		</div>
	);
}
